import { mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import {
  SOURCE_CODE_EXCLUDE_DIRS,
  SOURCE_CODE_EXTENSIONS,
  SOURCE_CODE_PER_FILE_CHARS,
  crawlSourceCode,
} from '../../src/cli/init-cli'

let tempDir: string

beforeEach(async () => {
  tempDir = await mkdtemp(path.join(os.tmpdir(), 'kb-crawl-test-'))
})

afterEach(async () => {
  await rm(tempDir, { recursive: true, force: true })
})

describe('crawlSourceCode', () => {
  it('Given a Python file, then includes it (not handled by ast-facts)', async () => {
    await writeFile(path.join(tempDir, 'main.py'), 'def hello(): pass', 'utf8')
    const result = await crawlSourceCode(tempDir)
    expect(result['main.py']).toBeDefined()
    expect(result['main.py']).toContain('def hello')
  })

  it('Given a TypeScript file, then excludes it (handled by ast-facts)', async () => {
    await writeFile(path.join(tempDir, 'index.ts'), 'export function hello() {}', 'utf8')
    const result = await crawlSourceCode(tempDir)
    expect(result['index.ts']).toBeUndefined()
  })

  it('Given a Go file, then excludes it (handled by ast-facts)', async () => {
    await writeFile(path.join(tempDir, 'main.go'), 'package main', 'utf8')
    const result = await crawlSourceCode(tempDir)
    expect(result['main.go']).toBeUndefined()
  })

  it('Given nested source files, then includes files from subdirectories', async () => {
    await mkdir(path.join(tempDir, 'src'))
    await writeFile(path.join(tempDir, 'src', 'utils.py'), 'x = 1', 'utf8')
    const result = await crawlSourceCode(tempDir)
    expect(result['src/utils.py']).toBeDefined()
  })

  it('Given a node_modules directory, then excludes it', async () => {
    await mkdir(path.join(tempDir, 'node_modules', 'some-pkg'), { recursive: true })
    await writeFile(path.join(tempDir, 'node_modules', 'some-pkg', 'index.py'), 'x=1', 'utf8')
    const result = await crawlSourceCode(tempDir)
    expect(Object.keys(result).some(k => k.includes('node_modules'))).toBe(false)
  })

  it('Given Jekyll output directories with source files, then excludes them', async () => {
    await mkdir(path.join(tempDir, 'docs', '_original_docs'), { recursive: true })
    await mkdir(path.join(tempDir, 'docs', '_autogenerated_docs'), { recursive: true })
    await mkdir(path.join(tempDir, 'docs', '_graph_pages'), { recursive: true })
    await writeFile(path.join(tempDir, 'docs', '_original_docs', 'copied.py'), 'x=1', 'utf8')
    await writeFile(path.join(tempDir, 'docs', '_autogenerated_docs', 'gen.py'), 'x=1', 'utf8')
    await writeFile(path.join(tempDir, 'docs', '_graph_pages', 'graph.py'), 'x=1', 'utf8')

    const result = await crawlSourceCode(tempDir)

    expect(Object.keys(result).some(k => k.includes('_original_docs'))).toBe(false)
    expect(Object.keys(result).some(k => k.includes('_autogenerated_docs'))).toBe(false)
    expect(Object.keys(result).some(k => k.includes('_graph_pages'))).toBe(false)
  })

  it('Given all excluded dirs, then none appear in result', async () => {
    for (const dir of SOURCE_CODE_EXCLUDE_DIRS) {
      await mkdir(path.join(tempDir, dir), { recursive: true })
      await writeFile(path.join(tempDir, dir, 'file.py'), 'x=1', 'utf8')
    }
    const result = await crawlSourceCode(tempDir)
    for (const dir of SOURCE_CODE_EXCLUDE_DIRS) {
      expect(Object.keys(result).some(k => k.startsWith(`${dir}/`))).toBe(false)
    }
  })

  it('Given a markdown file, then excludes it (not a source code extension)', async () => {
    await writeFile(path.join(tempDir, 'README.md'), '# Readme', 'utf8')
    await writeFile(path.join(tempDir, 'app.py'), 'x=1', 'utf8')
    const result = await crawlSourceCode(tempDir)
    expect(result['README.md']).toBeUndefined()
    expect(result['app.py']).toBeDefined()
  })

  it('Given a file longer than per-file char limit, then truncates content', async () => {
    const longContent = 'x'.repeat(SOURCE_CODE_PER_FILE_CHARS * 3)
    await writeFile(path.join(tempDir, 'big.py'), longContent, 'utf8')
    const result = await crawlSourceCode(tempDir)
    expect(result['big.py']).toBeDefined()
    expect(result['big.py']?.length).toBeLessThanOrEqual(SOURCE_CODE_PER_FILE_CHARS)
  })

  it('Given an empty directory, then returns empty object', async () => {
    const result = await crawlSourceCode(tempDir)
    expect(result).toEqual({})
  })

  it('Given dotfiles/dotdirs, then skips them', async () => {
    await mkdir(path.join(tempDir, '.hidden'))
    await writeFile(path.join(tempDir, '.hidden', 'secret.py'), 'x=1', 'utf8')
    const result = await crawlSourceCode(tempDir)
    expect(Object.keys(result).some(k => k.startsWith('.'))).toBe(false)
  })

  it('SOURCE_CODE_EXTENSIONS contains only non-ast-facts languages', () => {
    // ast-facts languages must NOT be in SOURCE_CODE_EXTENSIONS
    expect(SOURCE_CODE_EXTENSIONS).not.toContain('.ts')
    expect(SOURCE_CODE_EXTENSIONS).not.toContain('.tsx')
    expect(SOURCE_CODE_EXTENSIONS).not.toContain('.js')
    expect(SOURCE_CODE_EXTENSIONS).not.toContain('.go')
    // fallback languages must be present
    expect(SOURCE_CODE_EXTENSIONS).toContain('.py')
    expect(SOURCE_CODE_EXTENSIONS).toContain('.rb')
    expect(SOURCE_CODE_EXTENSIONS).toContain('.java')
  })
})
