import { mkdir, mkdtemp, readdir, rm, writeFile } from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import Database from '../../src/core/sqlite'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { parseJekyllPublishOptions, runJekyllPublish } from '../../src/cli/publish-jekyll'
import { docToCollectionFilename } from '../../src/core/publish/jekyll-sync'

let tempDir: string

beforeEach(async () => {
  tempDir = await mkdtemp(path.join(os.tmpdir(), 'kb-jekyll-cli-test-'))
})

afterEach(async () => {
  await rm(tempDir, { recursive: true, force: true })
})

function makeJekyllSite(root: string) {
  return writeFile(path.join(root, '_config.yml'), 'title: Test Site\n', 'utf8')
}

async function makeSqliteDb(
  baseDir: string,
  docs: Array<{ id: string; title: string; content: string; is_original?: number }>
) {
  const db = new Database(path.join(baseDir, '.kb-index.sqlite'))
  db.exec(`
    CREATE TABLE documents (
      id TEXT PRIMARY KEY,
      title TEXT NOT NULL,
      content TEXT NOT NULL,
      doc_type TEXT,
      lane TEXT,
      tags_json TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL,
      is_original INTEGER NOT NULL DEFAULT 0
    );
  `)
  const insert = db.prepare(
    'INSERT INTO documents (id, title, content, created_at, updated_at, is_original) VALUES (?, ?, ?, ?, ?, ?)'
  )
  for (const doc of docs) {
    insert.run(doc.id, doc.title, doc.content, '2026-01-15T10:00:00.000Z', '2026-01-15T10:00:00.000Z', doc.is_original ?? 0)
  }
  db.close()
}

describe('parseJekyllPublishOptions', () => {
  it('Given no flags, then defaults to dry-run and cwd for dir', () => {
    const opts = parseJekyllPublishOptions([], '/workspace')
    expect(opts.dryRun).toBe(true)
    expect(opts.apply).toBe(false)
    expect(opts.dir).toBe('/workspace')
  })

  it('Given --dir flag, then uses provided path', () => {
    const opts = parseJekyllPublishOptions(['--dir', '/my/jekyll'], '/workspace')
    expect(opts.dir).toBe('/my/jekyll')
  })

  it('Given --apply flag, then sets apply and clears dryRun', () => {
    const opts = parseJekyllPublishOptions(['--apply'], '/workspace')
    expect(opts.apply).toBe(true)
    expect(opts.dryRun).toBe(false)
  })

  it('Given both --apply and --dry-run, then throws', () => {
    expect(() => parseJekyllPublishOptions(['--apply', '--dry-run'], '/workspace')).toThrow(
      'Use either --apply or --dry-run, not both'
    )
  })
})

describe('runJekyllPublish dry-run', () => {
  it('Given a valid Jekyll dir and SQLite base, then returns dry-run result without writing files', async () => {
    const baseDir = path.join(tempDir, 'base')
    const siteDir = path.join(tempDir, 'site')
    await mkdir(baseDir, { recursive: true })
    await mkdir(siteDir, { recursive: true })
    await makeJekyllSite(siteDir)
    await makeSqliteDb(baseDir, [
      { id: 'doc-1', title: 'Hello World', content: '# Hello World\n\nBody.' },
    ])

    const result = await runJekyllPublish(
      { base: baseDir, dir: siteDir, apply: false, dryRun: true },
      tempDir
    )

    expect(result.status).toBe('dry-run')
    expect(result.totalDocs).toBe(1)
    expect(result.written).toHaveLength(1)
    expect(result.written[0].title).toBe('Hello World')
    // no _autogenerated_docs dir written in dry-run
    await expect(readdir(path.join(siteDir, '_autogenerated_docs'))).rejects.toThrow()
  })
})

describe('runJekyllPublish apply', () => {
  it('Given a valid Jekyll dir and SQLite base, then writes autogenerated_docs and returns accepted', async () => {
    const baseDir = path.join(tempDir, 'base')
    const siteDir = path.join(tempDir, 'site')
    await mkdir(baseDir, { recursive: true })
    await mkdir(siteDir, { recursive: true })
    await makeJekyllSite(siteDir)
    await makeSqliteDb(baseDir, [
      { id: 'doc-1', title: 'Hello World', content: '# Hello World\n\nBody.' },
      { id: 'doc-2', title: 'Second Doc', content: '# Second Doc\n\nMore content.' },
    ])

    const result = await runJekyllPublish(
      { base: baseDir, dir: siteDir, apply: true, dryRun: false },
      tempDir
    )

    expect(result.status).toBe('accepted')
    expect(result.totalDocs).toBe(2)
    expect(result.written).toHaveLength(2)
    expect(result.graphPagePath).toBe(path.join(siteDir, '_graph_pages/knowledge-graph.md'))
    expect(result.graphDataPath).toBe(path.join(siteDir, 'assets', 'generated', 'kb-graph.json'))

    const files = await readdir(path.join(siteDir, '_autogenerated_docs'))
    expect(files).toHaveLength(2)
    const graphPage = await readdir(path.join(siteDir, 'assets', 'generated'))
    expect(graphPage).toContain('kb-graph.json')
  })

  it('Given is_original docs, then routes them to _original_docs and autogenerated to _autogenerated_docs', async () => {
    const baseDir = path.join(tempDir, 'base')
    const siteDir = path.join(tempDir, 'site')
    await mkdir(baseDir, { recursive: true })
    await mkdir(siteDir, { recursive: true })
    await makeJekyllSite(siteDir)
    await makeSqliteDb(baseDir, [
      { id: 'orig-1', title: 'README', content: '# README\n\nProject docs.', is_original: 1 },
      { id: 'gen-1', title: 'Architecture Overview', content: '# Architecture\n\nGenerated.', is_original: 0 },
    ])

    await runJekyllPublish(
      { base: baseDir, dir: siteDir, apply: true, dryRun: false },
      tempDir
    )

    const originalFiles = await readdir(path.join(siteDir, '_original_docs'))
    const autogenFiles = await readdir(path.join(siteDir, '_autogenerated_docs'))
    expect(originalFiles).toHaveLength(1)
    expect(autogenFiles).toHaveLength(1)
  })

  it('Given a dir with no _config.yml, then throws with helpful error', async () => {
    const baseDir = path.join(tempDir, 'base')
    const siteDir = path.join(tempDir, 'no-jekyll')
    await mkdir(baseDir, { recursive: true })
    await mkdir(siteDir, { recursive: true })
    await makeSqliteDb(baseDir, [])

    await expect(
      runJekyllPublish({ base: baseDir, dir: siteDir, apply: false, dryRun: true }, tempDir)
    ).rejects.toThrow('No Jekyll project found')
  })

  it('Given an empty SQLite base, then returns warning about no docs', async () => {
    const baseDir = path.join(tempDir, 'base')
    const siteDir = path.join(tempDir, 'site')
    await mkdir(baseDir, { recursive: true })
    await mkdir(siteDir, { recursive: true })
    await makeJekyllSite(siteDir)
    await makeSqliteDb(baseDir, [])

    const result = await runJekyllPublish(
      { base: baseDir, dir: siteDir, apply: false, dryRun: true },
      tempDir
    )

    expect(result.warnings.some(w => w.includes('kb init'))).toBe(true)
  })
})

describe('docToCollectionFilename', () => {
  it('simple title becomes slug', () => {
    expect(docToCollectionFilename({ title: 'Agent Loop' })).toBe('agent-loop.md')
  })

  it('path-style title uses only the basename', () => {
    expect(docToCollectionFilename({ title: 'src/core/AGENT_LOOP.md' })).toBe('agent-loop.md')
  })

  it('strips .md extension from basename before slugifying', () => {
    expect(docToCollectionFilename({ title: 'README.md' })).toBe('readme.md')
  })

  it('nested path strips directory components and extension', () => {
    expect(docToCollectionFilename({ title: 'src/core/TUI.md' })).toBe('tui.md')
  })
})
