export interface SqliteDocumentRow {
  id: string
  title: string
  content: string
  doc_type: string | null
  lane: string | null
  tags_json: string | null
  created_at: string
  updated_at: string
  is_original: number
}

export type PublishPageRole = 'document' | 'section'

export interface PublishPageRecord {
  id: string
  title: string
  notionPageId?: string
  notionUrl?: string
  /** Section index pages split into the original-docs and autogenerated-docs lanes. */
  pageRole?: PublishPageRole
  /** Document lane; set for `pageRole === 'document'` (matches `is_original` split). */
  section?: 'original' | 'autogenerated'
}

/** Splits docs into the two publish lanes: original docs vs. autogenerated docs. */
export function partitionPublishDocsByOriginalFlag(docs: SqliteDocumentRow[]): {
  originals: SqliteDocumentRow[]
  autogenerated: SqliteDocumentRow[]
} {
  const originals = docs.filter(d => d.is_original === 1)
  const autogenerated = docs.filter(d => d.is_original !== 1)
  return { originals, autogenerated }
}
