/**
 * Normalize a raw file-path stem or ALL_CAPS/snake_case/kebab-case identifier
 * into a human-readable "Cap Every Word" title.
 *
 * Examples:
 *   "AGENTS.md"         → "Agents"
 *   "AGENT_LOOP"        → "Agent Loop"
 *   "src/core/TUI.md"   → "Tui"          (basename only — caller strips path first)
 *   "my-test-doc"       → "My Test Doc"
 *   "  hello  "         → "Hello"
 */
export function toTitleCase(raw: string): string {
  return raw
    .replace(/\.[^.]+$/, '') // strip file extension
    .replace(/[/_-]+/g, ' ') // replace separators with spaces
    .trim()
    .toLowerCase()
    .replace(/\b\w/g, c => c.toUpperCase())
}

/**
 * Return the bare filename (basename only, no path) for an original/source doc.
 * Preserves the original casing since these are raw files, not synthesized titles.
 *   "src/core/AGENT_LOOP.md" → "AGENT_LOOP.md"
 *   "CLAUDE.md"              → "CLAUDE.md"
 */
export function basenameTitle(filePath: string): string {
  return filePath.replace(/\\/g, '/').split('/').pop() ?? filePath
}

/**
 * Cap-every-word title for synthesized/autogenerated docs derived from a path stem.
 *   "src/core/AGENT_LOOP.md" → "Agent Loop"
 *   "CLAUDE.md"              → "Claude"
 *   "my-test-doc"            → "My Test Doc"
 */
export function titleFromFilePath(filePath: string): string {
  const basename = filePath.replace(/\\/g, '/').split('/').pop() ?? filePath
  return toTitleCase(basename)
}
