/**
 * Jekyll publish: markdown docs (original vs autogenerated lanes) plus **graph** JSON + graph page.
 * Notion publish mirrors doc lanes only; graph export for Notion is deferred (see `publish-cli.ts`).
 */
import { existsSync } from 'node:fs'
import path from 'node:path'
import Database from 'better-sqlite3'
import { discoverJekyllRoot, syncDocsToJekyll } from '../core/publish/jekyll-sync'
import { kbIndexDbPath } from '../tools/graph-query-expansion'
import { readDocumentsFromSqlite, resolvePublishBase } from './publish-cli'

export interface JekyllPublishOptions {
  base?: string
  dir: string
  apply: boolean
}

export interface JekyllPublishResult {
  status: 'accepted' | 'preview'
  jekyllRoot: string
  originalDocsDir: string
  autogeneratedDocsDir: string
  graphPagePath: string
  graphDataPath: string
  baseName: string
  baseDir: string
  totalDocs: number
  written: Array<{ id: string; title: string; filename: string }>
  skipped: Array<{ id: string; title: string; reason: string }>
  warnings: string[]
}

export function parseJekyllPublishOptions(args: string[], cwd: string): JekyllPublishOptions {
  const hasApply = readFlag(args, '--apply')
  return {
    base: readOption(args, '--base'),
    dir: readOption(args, '--dir') ?? cwd,
    apply: hasApply,
  }
}

export async function runJekyllPublish(
  options: JekyllPublishOptions,
  cwd: string = process.cwd()
): Promise<JekyllPublishResult> {
  const baseResolution = await resolvePublishBase(options.base, cwd)
  const sqliteDbPath = path.join(baseResolution.baseDir, '.kb-index.sqlite')
  const docs = readDocumentsFromSqlite(sqliteDbPath)

  const warnings: string[] = []
  if (docs.length === 0) {
    warnings.push('No documents found in SQLite database. Run `kb init` to populate.')
  }

  const jekyllRoot = await discoverJekyllRoot(path.resolve(options.dir))
  const graph = await readPublishedGraph(baseResolution.baseDir)
  const syncResult = await syncDocsToJekyll(docs, jekyllRoot, options.apply, graph)

  return {
    status: options.apply ? 'accepted' : 'preview',
    jekyllRoot: syncResult.jekyllRoot,
    originalDocsDir: syncResult.originalDocsDir,
    autogeneratedDocsDir: syncResult.autogeneratedDocsDir,
    graphPagePath: syncResult.graphPagePath,
    graphDataPath: syncResult.graphDataPath,
    baseName: baseResolution.baseName,
    baseDir: baseResolution.baseDir,
    totalDocs: docs.length,
    written: syncResult.written,
    skipped: syncResult.skipped,
    warnings,
  }
}

function readOption(args: string[], key: string): string | undefined {
  const idx = args.indexOf(key)
  if (idx === -1) return undefined
  const value = args[idx + 1]
  if (!value || value.startsWith('--')) {
    throw new Error(`${key} requires a value`)
  }
  return value
}

function readFlag(args: string[], key: string): boolean {
  return args.includes(key)
}

async function readPublishedGraph(baseDir: string) {
  const dbPath = kbIndexDbPath(baseDir)
  if (!existsSync(dbPath)) return undefined
  const db = new Database(dbPath, { readonly: true })
  try {
    const entities = db
      .prepare(
        `SELECT DISTINCT subject AS id, subject AS name FROM facts
         WHERE tombstoned_at IS NULL AND subject != 'kb' AND predicate != 'asserts'
         LIMIT 500`
      )
      .all() as Array<{ id: string; name: string }>
    const relationships = db
      .prepare(
        `SELECT subject AS fromId, predicate AS type, object AS toId FROM facts
         WHERE tombstoned_at IS NULL AND predicate != 'asserts' AND subject != 'kb'
         LIMIT 2000`
      )
      .all() as Array<{ fromId: string; type: string; toId: string }>
    return { generatedAt: new Date().toISOString(), entities, relationships }
  } finally {
    db.close()
  }
}
