import path from 'node:path'
import dayjs from 'dayjs'
import { SqliteKbIndexer } from '../tools/sqlite-kb-index'
import { ensureOperationalBaseDir, resolveEffectiveBaseDir } from './base-selection'
import { readKbConfig, resolveNotionToken } from './kb-config'

export type PublishPhase = 'all' | 'import' | 'restructure'
export type PublishStopPoint = string

export interface PublishOptions {
  base?: string
  phase: PublishPhase
  apply: boolean
  parentPageId?: string
  stagePageId?: string
  checkpointFile?: string
  resumeFrom?: string
  stopAfter?: PublishStopPoint
  progressSink?: (line: string) => void
}

export interface SqliteDocumentRow {
  id: string
  title: string
  content: string
  doc_type: string | null
  lane: string | null
  tags_json: string | null
  created_at: string
  updated_at: string
  is_original: number
}

export type PublishPageRole = 'document' | 'section'

export interface PublishPageRecord {
  id: string
  title: string
  notionPageId?: string
  notionUrl?: string
  /** Section index pages mirror Jekyll `_original_docs` / `_autogenerated_docs`. */
  pageRole?: PublishPageRole
  /** Document lane; set for `pageRole === 'document'` (matches `is_original` split). */
  section?: 'original' | 'autogenerated'
}

export interface PublishResult {
  status: 'accepted' | 'preview'
  apply: boolean
  baseName: string
  baseDir: string
  totalDocs: number
  publishedPages: PublishPageRecord[]
  warnings: string[]
}

const NOTION_VERSION = '2022-06-28'

class PublishProgressReporter {
  private completed = 0

  constructor(
    private total: number,
    private sink: (line: string) => void = line => process.stderr.write(line)
  ) {}

  start(label: string, detail?: string) {
    this.render(label, detail)
  }

  finish(label: string, detail?: string) {
    this.completed += 1
    this.render(label, detail)
  }

  update(label: string, detail?: string) {
    this.render(label, detail)
  }

  private render(label: string, detail?: string) {
    const width = 24
    const filled = Math.round((this.completed / Math.max(this.total, 1)) * width)
    const bar = `${'='.repeat(filled)}${'-'.repeat(Math.max(width - filled, 0))}`
    const suffix = detail ? ` ${detail}` : ''
    this.sink(`[publish] [${bar}] ${this.completed}/${this.total} ${label}${suffix}\n`)
  }
}

export function parsePublishCommand(args: string[]): PublishOptions {
  const hasApply = readFlag(args, '--apply')
  const phase = (readOption(args, '--phase') ?? 'all') as PublishPhase
  if (!['all', 'import', 'restructure'].includes(phase)) {
    throw new Error('Invalid --phase. Use all|import|restructure')
  }

  const stopAfter = readOption(args, '--stop-after')?.trim().toLowerCase()

  return {
    base: readOption(args, '--base'),
    phase,
    apply: hasApply,
    parentPageId: readOption(args, '--parent-page-id'),
    stagePageId: readOption(args, '--stage-page-id'),
    checkpointFile: readOption(args, '--checkpoint-file'),
    resumeFrom: readOption(args, '--resume-from'),
    stopAfter,
  }
}

export async function runPublishCommand(
  options: PublishOptions,
  cwd: string = process.cwd()
): Promise<PublishResult> {
  const config = await readKbConfig()
  const baseResolution = await resolvePublishBase(options.base, cwd)
  const warnings: string[] = []

  const token = options.apply ? resolveNotionToken(config) : undefined
  if (options.apply && !token) {
    throw new Error(
      'Missing Notion token. Set notion.token in ~/.kb/config.json or NOTION_TOKEN/NOTION_API_KEY in env.'
    )
  }

  const parentPageId =
    options.parentPageId ?? config.notion?.parentPageId ?? process.env.NOTION_PARENT_PAGE_ID

  if (options.apply && !parentPageId) {
    throw new Error(
      'Missing Notion parent page ID. Set notion.parentPageId in ~/.kb/config.json or --parent-page-id flag.'
    )
  }

  // Read documents from SQLite (same split as `publish jekyll`: originals vs autogenerated markdown).
  // Graph export: Jekyll only for now (`publish-jekyll`); Notion parity TBD (API / layout).
  const sqliteDbPath = path.join(baseResolution.baseDir, '.kb-index.sqlite')
  const docs = readDocumentsFromSqlite(sqliteDbPath)
  const { originals, autogenerated } = partitionPublishDocsByOriginalFlag(docs)

  if (docs.length === 0) {
    warnings.push('No documents found in SQLite database. Run `kb init` to populate.')
  }

  const progressTotal = 2 + docs.length
  const progress = new PublishProgressReporter(progressTotal, options.progressSink)
  progress.start('reading docs', `${docs.length} documents`)

  const publishedPages: PublishResult['publishedPages'] = []

  if (!options.apply) {
    publishedPages.push({
      id: 'section-original-documents',
      title: 'Original Documents',
      pageRole: 'section',
      section: 'original',
    })
    publishedPages.push({
      id: 'section-autogenerated-documents',
      title: 'Autogenerated Documents',
      pageRole: 'section',
      section: 'autogenerated',
    })
    progress.finish('preview', 'Original Documents')
    progress.finish('preview', 'Autogenerated Documents')
    for (const doc of originals) {
      publishedPages.push({
        id: doc.id,
        title: doc.title,
        section: 'original',
        pageRole: 'document',
      })
      progress.finish('preview', doc.title)
    }
    for (const doc of autogenerated) {
      publishedPages.push({
        id: doc.id,
        title: doc.title,
        section: 'autogenerated',
        pageRole: 'document',
      })
      progress.finish('preview', doc.title)
    }

    return {
      status: 'preview',
      apply: false,

      baseName: baseResolution.baseName,
      baseDir: baseResolution.baseDir,
      totalDocs: docs.length,
      publishedPages,
      warnings,
    }
  }

  if (!token || !parentPageId) {
    throw new Error('Notion token and parent page ID are required to publish.')
  }

  // Create a parent page for this base's documents
  const runTimestamp = dayjs().format('YYYY-MM-DD HH:mm')
  const containerPage = await notionCreatePage({
    token,
    parentPageId,
    title: `${baseResolution.baseName} — ${runTimestamp}`,
  })

  progress.update('created container page', containerPage.url)

  const originalSection = await notionCreatePage({
    token,
    parentPageId: containerPage.id,
    title: 'Original Documents',
  })
  publishedPages.push({
    id: 'section-original-documents',
    title: 'Original Documents',
    notionPageId: originalSection.id,
    notionUrl: originalSection.url,
    pageRole: 'section',
    section: 'original',
  })
  progress.finish('section', 'Original Documents')

  const autogeneratedSection = await notionCreatePage({
    token,
    parentPageId: containerPage.id,
    title: 'Autogenerated Documents',
  })
  publishedPages.push({
    id: 'section-autogenerated-documents',
    title: 'Autogenerated Documents',
    notionPageId: autogeneratedSection.id,
    notionUrl: autogeneratedSection.url,
    pageRole: 'section',
    section: 'autogenerated',
  })
  progress.finish('section', 'Autogenerated Documents')

  for (const doc of originals) {
    try {
      const page = await notionCreatePage({
        token,
        parentPageId: originalSection.id,
        title: doc.title,
        markdown: doc.content,
      })
      publishedPages.push({
        id: doc.id,
        title: doc.title,
        notionPageId: page.id,
        notionUrl: page.url,
        pageRole: 'document',
        section: 'original',
      })
      progress.finish('published', doc.title)
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err)
      warnings.push(`Failed to publish original "${doc.title}": ${msg}`)
      progress.finish('failed', doc.title)
    }
  }

  for (const doc of autogenerated) {
    try {
      const page = await notionCreatePage({
        token,
        parentPageId: autogeneratedSection.id,
        title: doc.title,
        markdown: doc.content,
      })
      publishedPages.push({
        id: doc.id,
        title: doc.title,
        notionPageId: page.id,
        notionUrl: page.url,
        pageRole: 'document',
        section: 'autogenerated',
      })
      progress.finish('published', doc.title)
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err)
      warnings.push(`Failed to publish autogenerated "${doc.title}": ${msg}`)
      progress.finish('failed', doc.title)
    }
  }

  return {
    status: 'accepted',
    apply: true,
    baseName: baseResolution.baseName,
    baseDir: baseResolution.baseDir,
    totalDocs: docs.length,
    publishedPages,
    warnings,
  }
}

/** Same lane split as Jekyll `_original_docs` / `_autogenerated_docs` (`jekyll-sync.ts`). */
export function partitionPublishDocsByOriginalFlag(docs: SqliteDocumentRow[]): {
  originals: SqliteDocumentRow[]
  autogenerated: SqliteDocumentRow[]
} {
  const originals = docs.filter(d => d.is_original === 1)
  const autogenerated = docs.filter(d => d.is_original !== 1)
  return { originals, autogenerated }
}

// ─── SQLite read ────────────────────────────────────────────────────────────

export function readDocumentsFromSqlite(dbPath: string): SqliteDocumentRow[] {
  try {
    const indexer = new SqliteKbIndexer({ dbPath })
    const docs = indexer.listPublishableDocs()
    indexer.close()
    return docs
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    throw new Error(`Cannot read SQLite at ${dbPath}: ${msg}`)
  }
}

// ─── Notion API ─────────────────────────────────────────────────────────────

async function notionCreatePage(input: {
  token: string
  parentPageId?: string
  title: string
  asWorkspaceRoot?: boolean
  markdown?: string
}): Promise<{ id: string; url: string }> {
  const parent = input.asWorkspaceRoot ? { workspace: true } : { page_id: input.parentPageId }

  const response = await fetch('https://api.notion.com/v1/pages', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${input.token}`,
      'Notion-Version': NOTION_VERSION,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      parent,
      properties: {
        title: {
          title: [
            {
              type: 'text',
              text: { content: input.title.slice(0, 200) },
            },
          ],
        },
      },
      ...(input.markdown ? { markdown: input.markdown } : {}),
    }),
  })

  if (!response.ok) {
    const body = await response.text()
    if (response.status === 400 && body.includes('public integration')) {
      throw new Error(
        'Notion workspace-root page creation is not supported for internal integrations. ' +
          'Set notion.parentPageId in ~/.kb/config.json.'
      )
    }
    throw new Error(`Notion create page failed (${response.status}): ${body}`)
  }

  const parsed = (await response.json()) as { id?: string; url?: string }
  if (!parsed.id || !parsed.url) {
    throw new Error('Notion create page response missing id/url')
  }

  return { id: parsed.id, url: parsed.url }
}

// ─── Config & resolution helpers ─────────────────────────────────────────────

export async function resolvePublishBase(
  base: string | undefined,
  cwd: string
): Promise<{ baseName: string; baseDir: string }> {
  if (base?.trim()) {
    return {
      baseName: base.trim(),
      baseDir: await ensureOperationalBaseDir(base.trim(), cwd),
    }
  }

  const resolved = await resolveEffectiveBaseDir(cwd)
  return {
    baseName: resolved.baseName ?? 'default',
    baseDir: resolved.baseDir,
  }
}

// ─── Arg parsing helpers ──────────────────────────────────────────────────────

function readOption(args: string[], key: string): string | undefined {
  const idx = args.indexOf(key)
  if (idx === -1) return undefined
  const value = args[idx + 1]
  if (!value || value.startsWith('--')) {
    throw new Error(`${key} requires a value`)
  }
  return value
}

function readFlag(args: string[], key: string): boolean {
  return args.includes(key)
}
