import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { syncDocsToNotion } from '../../src/core/publish/notion-sync'
import type { SqliteDocumentRow } from '../../src/core/publish/publish-docs'
import { notionPublishStatePath } from '../../src/core/publish/publish-state'

const makeDoc = (overrides: Partial<SqliteDocumentRow> = {}): SqliteDocumentRow => ({
  id: 'doc-1',
  title: 'My Test Document',
  content: '# My Test Document\n\nBody.',
  doc_type: null,
  lane: null,
  tags_json: null,
  created_at: '2026-01-15T10:00:00.000Z',
  updated_at: '2026-01-15T10:00:00.000Z',
  is_original: 0,
  ...overrides,
})

let tempDir: string
let fetchMock: ReturnType<typeof vi.fn>

beforeEach(async () => {
  tempDir = await mkdtemp(path.join(os.tmpdir(), 'kb-notion-sync-test-'))
  fetchMock = vi.fn()
  vi.stubGlobal('fetch', fetchMock)
})

afterEach(async () => {
  vi.unstubAllGlobals()
  await rm(tempDir, { recursive: true, force: true })
})

function mockJsonResponse(body: unknown, status = 200): Response {
  return {
    ok: status >= 200 && status < 300,
    status,
    json: async () => body,
    text: async () => JSON.stringify(body),
  } as Response
}

describe('syncDocsToNotion preview', () => {
  it('Given existing state with stale pages, then reports removed titles', async () => {
    await writeFile(
      notionPublishStatePath(tempDir),
      `${JSON.stringify({
        version: 1,
        updatedAt: '2026-01-01T00:00:00.000Z',
        baseName: 'dogfood',
        containerPageId: 'container-1',
        originalSectionPageId: 'section-original',
        autogeneratedSectionPageId: 'section-autogen',
      })}\n`,
      'utf8'
    )

    fetchMock.mockImplementation(async (input: RequestInfo | URL) => {
      const url = String(input)
      if (url.includes('/blocks/section-original/children')) {
        return mockJsonResponse({
          results: [{ id: 'page-old', type: 'child_page' }],
          has_more: false,
        })
      }
      if (url.includes('/blocks/section-autogen/children')) {
        return mockJsonResponse({ results: [], has_more: false })
      }
      if (url.includes('/pages/page-old')) {
        return mockJsonResponse({
          properties: { title: { title: [{ plain_text: 'Stale Doc' }] } },
        })
      }
      throw new Error(`Unexpected fetch: ${url}`)
    })

    const result = await syncDocsToNotion({
      token: 'token',
      parentPageId: 'parent-1',
      baseName: 'dogfood',
      baseDir: tempDir,
      docs: [makeDoc()],
      apply: false,
    })

    expect(result.removed).toEqual([
      { id: 'page-old', title: 'Stale Doc', section: 'original' },
    ])
    expect(result.written).toHaveLength(1)
  })
})

describe('syncDocsToNotion apply', () => {
  it('Given existing section pages, then archives stale children and recreates current docs', async () => {
    await mkdir(tempDir, { recursive: true })
    await writeFile(
      notionPublishStatePath(tempDir),
      `${JSON.stringify({
        version: 1,
        updatedAt: '2026-01-01T00:00:00.000Z',
        baseName: 'dogfood',
        containerPageId: 'container-1',
        containerUrl: 'https://notion.so/container-1',
        originalSectionPageId: 'section-original',
        autogeneratedSectionPageId: 'section-autogen',
      })}\n`,
      'utf8'
    )

    const archived: string[] = []
    const created: string[] = []

    fetchMock.mockImplementation(async (input: RequestInfo | URL, init?: RequestInit) => {
      const url = String(input)
      const method = init?.method ?? 'GET'

      if (url.includes('/blocks/section-original/children') || url.includes('/blocks/section-autogen/children')) {
        const section = url.includes('section-original') ? 'section-original' : 'section-autogen'
        if (section === 'section-original') {
          return mockJsonResponse({
            results: [{ id: 'page-old', type: 'child_page' }],
            has_more: false,
          })
        }
        return mockJsonResponse({ results: [], has_more: false })
      }

      if (url.includes('/pages/page-old') && method === 'GET') {
        return mockJsonResponse({
          properties: { title: { title: [{ plain_text: 'Stale Doc' }] } },
        })
      }

      if (method === 'PATCH' && url.includes('/pages/page-old')) {
        archived.push('page-old')
        return mockJsonResponse({ id: 'page-old' })
      }

      if (method === 'POST' && url.endsWith('/v1/pages')) {
        const body = JSON.parse(String(init?.body)) as {
          parent?: { page_id?: string }
          properties?: { title?: { title?: Array<{ text?: { content?: string } }> } }
        }
        const title = body.properties?.title?.title?.[0]?.text?.content ?? 'untitled'
        created.push(`${body.parent?.page_id}:${title}`)
        return mockJsonResponse({
          id: `new-${created.length}`,
          url: `https://notion.so/new-${created.length}`,
        })
      }

      throw new Error(`Unexpected fetch: ${method} ${url}`)
    })

    const result = await syncDocsToNotion({
      token: 'token',
      parentPageId: 'parent-1',
      baseName: 'dogfood',
      baseDir: tempDir,
      docs: [makeDoc()],
      apply: true,
    })

    expect(archived).toEqual(['page-old'])
    expect(created).toEqual(['section-autogen:My Test Document'])
    expect(result.removed).toEqual([
      { id: 'page-old', title: 'Stale Doc', section: 'original' },
    ])
    expect(result.publishedPages.some(p => p.id === 'doc-1')).toBe(true)
  })

  it('Given no state file, then creates container and section pages once', async () => {
    fetchMock.mockImplementation(async (input: RequestInfo | URL, init?: RequestInit) => {
      const url = String(input)
      const method = init?.method ?? 'GET'

      if (method === 'POST' && url.endsWith('/v1/pages')) {
        const body = JSON.parse(String(init?.body)) as {
          properties?: { title?: { title?: Array<{ text?: { content?: string } }> } }
        }
        const title = body.properties?.title?.title?.[0]?.text?.content ?? 'untitled'
        const id = `page-${title.replace(/\s+/g, '-').toLowerCase()}`
        return mockJsonResponse({ id, url: `https://notion.so/${id}` })
      }

      if (url.includes('/blocks/') && url.includes('/children')) {
        return mockJsonResponse({ results: [], has_more: false })
      }

      throw new Error(`Unexpected fetch: ${method} ${url}`)
    })

    await syncDocsToNotion({
      token: 'token',
      parentPageId: 'parent-1',
      baseName: 'dogfood',
      baseDir: tempDir,
      docs: [makeDoc({ is_original: 1 })],
      apply: true,
    })

    const state = JSON.parse(await readFile(notionPublishStatePath(tempDir), 'utf8')) as {
      containerPageId?: string
      originalSectionPageId?: string
      autogeneratedSectionPageId?: string
    }
    expect(state.containerPageId).toBeTruthy()
    expect(state.originalSectionPageId).toBeTruthy()
    expect(state.autogeneratedSectionPageId).toBeTruthy()
  })
})
