import { describe, expect, it } from 'vitest'
import {
  partitionPublishDocsByOriginalFlag,
  type SqliteDocumentRow,
} from '../../src/core/publish/publish-docs'

const row = (id: string, isOriginal: number): SqliteDocumentRow => ({
  id,
  title: id,
  content: '',
  doc_type: null,
  lane: null,
  tags_json: null,
  created_at: '',
  updated_at: '',
  is_original: isOriginal,
})

describe('partitionPublishDocsByOriginalFlag', () => {
  it('splits originals vs autogenerated by is_original', () => {
    const docs = [row('a', 1), row('b', 0), row('c', 1)]
    const { originals, autogenerated } = partitionPublishDocsByOriginalFlag(docs)
    expect(originals.map(d => d.id)).toEqual(['a', 'c'])
    expect(autogenerated.map(d => d.id)).toEqual(['b'])
  })
})
