import { mkdir, readdir, rm, stat, writeFile } from 'node:fs/promises'
import path from 'node:path'
import yaml from 'js-yaml'

export interface KbDocRow {
  id: string
  title: string
  content: string
  doc_type: string | null
  tags_json: string | null
  created_at: string
  updated_at: string
  is_original: number
}

export interface JekyllSyncResult {
  jekyllRoot: string
  originalDocsDir: string
  autogeneratedDocsDir: string
  written: Array<{ id: string; title: string; filename: string }>
  skipped: Array<{ id: string; title: string; reason: string }>
}

export async function discoverJekyllRoot(dir: string): Promise<string> {
  const candidates = [dir, path.join(dir, 'docs')]
  for (const candidate of candidates) {
    try {
      await stat(path.join(candidate, '_config.yml'))
      return candidate
    } catch {
      // not here, try next
    }
  }
  throw new Error(
    `No Jekyll project found. Looked for _config.yml in:\n  ${candidates.join('\n  ')}`
  )
}

export async function syncDocsToJekyll(
  docs: KbDocRow[],
  jekyllRoot: string,
  dryRun = false
): Promise<JekyllSyncResult> {
  const originalDocsDir = path.join(jekyllRoot, '_original_docs')
  const autogeneratedDocsDir = path.join(jekyllRoot, '_autogenerated_docs')
  const written: JekyllSyncResult['written'] = []
  const skipped: JekyllSyncResult['skipped'] = []

  if (dryRun) {
    const originalSlugsSeen = new Set<string>()
    const autogeneratedSlugsSeen = new Set<string>()
    for (const doc of docs) {
      if (!doc.title?.trim()) {
        skipped.push({ id: doc.id, title: '', reason: 'no title' })
        continue
      }
      const slugsSeen = doc.is_original === 1 ? originalSlugsSeen : autogeneratedSlugsSeen
      const filename = deduplicateFilename(docToCollectionFilename(doc), slugsSeen)
      slugsSeen.add(filename)
      written.push({ id: doc.id, title: doc.title, filename })
    }
    return { jekyllRoot, originalDocsDir, autogeneratedDocsDir, written, skipped }
  }

  await mkdir(originalDocsDir, { recursive: true })
  await mkdir(autogeneratedDocsDir, { recursive: true })

  for (const dir of [originalDocsDir, autogeneratedDocsDir]) {
    const existing = await readdir(dir)
    await Promise.all(existing.filter(f => f.endsWith('.md')).map(f => rm(path.join(dir, f))))
  }

  const originalSlugsSeen = new Set<string>()
  const autogeneratedSlugsSeen = new Set<string>()

  for (const doc of docs) {
    if (!doc.title?.trim()) {
      skipped.push({ id: doc.id, title: '', reason: 'no title' })
      continue
    }

    const isOriginal = doc.is_original === 1
    const slugsSeen = isOriginal ? originalSlugsSeen : autogeneratedSlugsSeen
    const targetDir = isOriginal ? originalDocsDir : autogeneratedDocsDir
    const filename = deduplicateFilename(docToCollectionFilename(doc), slugsSeen)
    slugsSeen.add(filename)
    await writeFile(path.join(targetDir, filename), buildJekyllFile(doc), 'utf8')
    written.push({ id: doc.id, title: doc.title, filename })
  }

  const originalEntries = written
    .filter(({ id }) => docs.find(d => d.id === id)?.is_original === 1)
    .map(({ title, filename }) => ({ title, filename }))

  const autogeneratedEntries = written
    .filter(({ id }) => docs.find(d => d.id === id)?.is_original !== 1)
    .map(({ title, filename }) => ({ title, filename }))

  await writeCollectionData(jekyllRoot, 'kb_original_docs.yml', originalEntries)
  await writeCollectionData(jekyllRoot, 'kb_autogenerated_docs.yml', autogeneratedEntries)

  return { jekyllRoot, originalDocsDir, autogeneratedDocsDir, written, skipped }
}

export function docToCollectionFilename(doc: Pick<KbDocRow, 'title'>): string {
  const basename = path.basename(doc.title).replace(/\.[^.]+$/, '') || doc.title
  return `${slugify(basename)}.md`
}

export function filenameToCollectionUrlPath(filename: string): string {
  const slug = filename.replace(/\.md$/i, '')
  return `/${slug}.html`
}

async function writeCollectionData(
  jekyllRoot: string,
  filename: string,
  entries: Array<{ title: string; filename: string }>
): Promise<void> {
  const dataDir = path.join(jekyllRoot, '_data')
  await mkdir(dataDir, { recursive: true })
  const docs = entries.map(({ title, filename: f }) => ({
    title,
    url: filenameToCollectionUrlPath(f),
  }))
  const out = `# Auto-generated by kb publish jekyll — do not edit by hand\n${yaml.dump({ docs }, { lineWidth: -1 })}`
  await writeFile(path.join(dataDir, filename), out, 'utf8')
}

export function slugify(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80)
}

export function buildJekyllFile(doc: KbDocRow): string {
  const frontMatter = mapToJekyllFrontMatter(doc)
  const body = stripKbMetadataHeader(doc.content)
  return `---\n${yaml.dump(frontMatter, { lineWidth: -1 }).trimEnd()}\n---\n\n${body.trimStart()}`
}

export function mapToJekyllFrontMatter(doc: KbDocRow): Record<string, unknown> {
  const tags = parseTags(doc.tags_json)
  const fm: Record<string, unknown> = {
    layout: 'default',
    title: doc.title,
    date: doc.created_at.slice(0, 19).replace('T', ' '),
    kb_id: doc.id,
  }
  if (tags.length > 0) fm.tags = tags
  if (doc.doc_type) fm.categories = [doc.doc_type]
  return fm
}

export function stripKbMetadataHeader(content: string): string {
  const lines = content.split('\n')
  let i = 0

  // skip H1 title line
  if (lines[i]?.startsWith('# ')) i++

  // skip blank lines then metadata key-value lines (Created:, Type:, Tags:)
  while (i < lines.length) {
    const line = lines[i]
    if (line.trim() === '') {
      i++
      continue
    }
    if (/^(Created|Type|Tags): /.test(line)) {
      i++
      continue
    }
    break
  }

  return lines.slice(i).join('\n')
}

function parseTags(tagsJson: string | null): string[] {
  if (!tagsJson) return []
  try {
    const parsed = JSON.parse(tagsJson)
    return Array.isArray(parsed) ? parsed.map(String) : []
  } catch {
    return []
  }
}

function deduplicateFilename(base: string, seen: Set<string>): string {
  if (!seen.has(base)) return base
  const ext = path.extname(base)
  const stem = base.slice(0, -ext.length)
  let n = 2
  while (seen.has(`${stem}-${n}${ext}`)) n++
  return `${stem}-${n}${ext}`
}
