import { mkdir, readdir, rm, stat, writeFile } from 'node:fs/promises'
import path from 'node:path'
import yaml from 'js-yaml'
import type { GraphEntity, GraphRelationship } from '../../tools/kb-graph-writer'

/**
 * Publish splits the KB into two Jekyll lanes only:
 * - `is_original === 1` → `_original_docs/` — **frozen snapshots** of repo/source material. We
 *   surface them as-is for reference; init and retrieval do **not** try to critique, merge, or
 *   “fix up” originals against autogen.
 * - `is_original !== 1` → `_autogenerated_docs/` — LLM-authored KB docs (the curated layer we
 *   refine and show off). They may repeat or overlap originals; there is no cross-lane dedupe.
 */
export interface KbDocRow {
  id: string
  title: string
  content: string
  doc_type: string | null
  tags_json: string | null
  created_at: string
  updated_at: string
  is_original: number
}

export interface JekyllSyncResult {
  jekyllRoot: string
  originalDocsDir: string
  autogeneratedDocsDir: string
  graphPagePath: string
  graphDataPath: string
  written: Array<{ id: string; title: string; filename: string }>
  skipped: Array<{ id: string; title: string; reason: string }>
}

export interface JekyllGraphPayload {
  generatedAt: string
  entities: GraphEntity[]
  relationships: GraphRelationship[]
}

export async function discoverJekyllRoot(dir: string): Promise<string> {
  const candidates = [dir, path.join(dir, 'docs')]
  for (const candidate of candidates) {
    try {
      await stat(path.join(candidate, '_config.yml'))
      return candidate
    } catch {
      // not here, try next
    }
  }
  throw new Error(
    `No Jekyll project found. Looked for _config.yml in:\n  ${candidates.join('\n  ')}`
  )
}

export async function syncDocsToJekyll(
  docs: KbDocRow[],
  jekyllRoot: string,
  dryRun = false,
  graph?: JekyllGraphPayload
): Promise<JekyllSyncResult> {
  const originalDocsDir = path.join(jekyllRoot, '_original_docs')
  const autogeneratedDocsDir = path.join(jekyllRoot, '_autogenerated_docs')
  const graphPagesDir = path.join(jekyllRoot, '_graph_pages')
  const graphPagePath = path.join(graphPagesDir, 'knowledge-graph.md')
  const graphDataPath = path.join(jekyllRoot, 'assets', 'generated', 'kb-graph.json')
  const written: JekyllSyncResult['written'] = []
  const skipped: JekyllSyncResult['skipped'] = []

  if (dryRun) {
    const originalSlugsSeen = new Set<string>()
    const autogeneratedSlugsSeen = new Set<string>()
    for (const doc of docs) {
      if (!doc.title?.trim()) {
        skipped.push({ id: doc.id, title: '', reason: 'no title' })
        continue
      }
      const slugsSeen = doc.is_original === 1 ? originalSlugsSeen : autogeneratedSlugsSeen
      const filename = deduplicateFilename(docToCollectionFilename(doc), slugsSeen)
      slugsSeen.add(filename)
      written.push({ id: doc.id, title: doc.title, filename })
    }
    return {
      jekyllRoot,
      originalDocsDir,
      autogeneratedDocsDir,
      graphPagePath,
      graphDataPath,
      written,
      skipped,
    }
  }

  await mkdir(originalDocsDir, { recursive: true })
  await mkdir(autogeneratedDocsDir, { recursive: true })
  await mkdir(graphPagesDir, { recursive: true })

  for (const dir of [originalDocsDir, autogeneratedDocsDir, graphPagesDir]) {
    const existing = await readdir(dir)
    await Promise.all(existing.filter(f => f.endsWith('.md')).map(f => rm(path.join(dir, f))))
  }

  const originalSlugsSeen = new Set<string>()
  const autogeneratedSlugsSeen = new Set<string>()
  const publishedAtMs = Date.now()

  for (const doc of docs) {
    if (!doc.title?.trim()) {
      skipped.push({ id: doc.id, title: '', reason: 'no title' })
      continue
    }

    const isOriginal = doc.is_original === 1
    const slugsSeen = isOriginal ? originalSlugsSeen : autogeneratedSlugsSeen
    const targetDir = isOriginal ? originalDocsDir : autogeneratedDocsDir
    const filename = deduplicateFilename(docToCollectionFilename(doc), slugsSeen)
    slugsSeen.add(filename)
    await writeFile(path.join(targetDir, filename), buildJekyllFile(doc, { publishedAtMs }), 'utf8')
    written.push({ id: doc.id, title: doc.title, filename })
  }

  const originalEntries = written
    .filter(({ id }) => docs.find(d => d.id === id)?.is_original === 1)
    .map(({ title, filename }) => ({ title, filename }))

  const autogeneratedEntries = written
    .filter(({ id }) => docs.find(d => d.id === id)?.is_original !== 1)
    .map(({ title, filename }) => ({ title, filename }))

  await writeCollectionData(jekyllRoot, 'kb_original_docs.yml', originalEntries)
  await writeCollectionData(jekyllRoot, 'kb_autogenerated_docs.yml', autogeneratedEntries)
  await writeGraphArtifacts(jekyllRoot, graph)

  return {
    jekyllRoot,
    originalDocsDir,
    autogeneratedDocsDir,
    graphPagePath,
    graphDataPath,
    written,
    skipped,
  }
}

export function docToCollectionFilename(doc: Pick<KbDocRow, 'title'>): string {
  const basename = path.basename(doc.title).replace(/\.[^.]+$/, '') || doc.title
  return `${slugify(basename)}.md`
}

export function filenameToCollectionUrlPath(filename: string): string {
  const slug = filename.replace(/\.md$/i, '')
  return `/${slug}.html`
}

async function writeCollectionData(
  jekyllRoot: string,
  filename: string,
  entries: Array<{ title: string; filename: string }>
): Promise<void> {
  const dataDir = path.join(jekyllRoot, '_data')
  await mkdir(dataDir, { recursive: true })
  const docs = entries.map(({ title, filename: f }) => ({
    title,
    url: filenameToCollectionUrlPath(f),
  }))
  const out = `# Auto-generated by kb publish jekyll — do not edit by hand\n${yaml.dump({ docs }, { lineWidth: -1 })}`
  await writeFile(path.join(dataDir, filename), out, 'utf8')
}

async function writeGraphArtifacts(jekyllRoot: string, graph?: JekyllGraphPayload): Promise<void> {
  const graphPagePath = path.join(jekyllRoot, '_graph_pages', 'knowledge-graph.md')
  const graphDataDir = path.join(jekyllRoot, 'assets', 'generated')
  await mkdir(graphDataDir, { recursive: true })

  const payload: JekyllGraphPayload = graph ?? {
    generatedAt: new Date().toISOString(),
    entities: [],
    relationships: [],
  }

  await writeFile(
    path.join(graphDataDir, 'kb-graph.json'),
    JSON.stringify(payload, null, 2),
    'utf8'
  )
  await writeFile(graphPagePath, buildGraphPageMarkdown(), 'utf8')
}

function buildGraphPageMarkdown(): string {
  return `---
layout: default
title: Knowledge Graph
permalink: /graph.html
nav_order: 1
---

# Knowledge Graph

This page renders the current published KB graph using Cytoscape.js.

<div id="kb-graph-meta" style="margin-bottom: 1rem; color: #666;">Loading graph…</div>
<div id="kb-graph" style="width: 100%; height: 80vh; min-height: 720px; border: 1px solid #e5e7eb; border-radius: 12px;"></div>

<script src="https://unpkg.com/cytoscape@3.30.2/dist/cytoscape.min.js"></script>
<script>
  async function loadKbGraph() {
    const meta = document.getElementById('kb-graph-meta')
    const container = document.getElementById('kb-graph')

    try {
      const response = await fetch('{{ "/assets/generated/kb-graph.json" | relative_url }}')
      if (!response.ok) {
        throw new Error('Graph data request failed with status ' + response.status)
      }

      const payload = await response.json()
      const entities = Array.isArray(payload.entities) ? payload.entities : []
      const relationships = Array.isArray(payload.relationships) ? payload.relationships : []

      meta.textContent =
        entities.length === 0 && relationships.length === 0
          ? 'No graph data has been published yet. Run kb init, then kb publish jekyll --apply.'
          : entities.length + ' nodes, ' + relationships.length + ' edges. Click a node to focus its neighborhood.'

      const elements = [
        ...entities.map(entity => ({
          data: {
            id: entity.id,
            label: entity.name || entity.id,
            type: entity.type || 'concept',
          },
        })),
        ...relationships.map((relationship, index) => ({
          data: {
            id: relationship.fromId + '__' + relationship.type + '__' + relationship.toId + '__' + index,
            source: relationship.fromId,
            target: relationship.toId,
            label: relationship.type,
          },
        })),
      ]

      const cy = cytoscape({
        container,
        elements,
        layout: {
          name: 'cose',
          animate: false,
          fit: true,
          padding: 140,
          randomize: true,
          componentSpacing: 220,
          nodeRepulsion: 280000,
          idealEdgeLength: 120,
          edgeElasticity: 80,
          nestingFactor: 0.8,
          gravity: 0.1,
          numIter: 2200,
          initialTemp: 180,
          coolingFactor: 0.96,
          minTemp: 1,
        },
        wheelSensitivity: 0.18,
        minZoom: 0.08,
        maxZoom: 3,
        style: [
          {
            selector: 'node',
            style: {
              'background-color': '#2563eb',
              color: '#0f172a',
              label: 'data(label)',
              'font-size': 8,
              'min-zoomed-font-size': 7,
              'text-wrap': 'wrap',
              'text-max-width': 72,
              'text-valign': 'bottom',
              'text-margin-y': 8,
              width: 12,
              height: 12,
            },
          },
          {
            selector: 'node[type = "system"]',
            style: { 'background-color': '#0f766e' },
          },
          {
            selector: 'node[type = "tool"]',
            style: { 'background-color': '#7c3aed' },
          },
          {
            selector: 'node[type = "decision"]',
            style: { 'background-color': '#b45309' },
          },
          {
            selector: 'node[type = "person"]',
            style: { 'background-color': '#be123c' },
          },
          {
            selector: 'node.focused',
            style: {
              'border-width': 2,
              'border-color': '#f8fafc',
              width: 16,
              height: 16,
            },
          },
          {
            selector: '.dimmed',
            style: {
              opacity: 0.14,
            },
          },
          {
            selector: 'edge',
            style: {
              width: 1,
              'line-color': '#94a3b8',
              'target-arrow-color': '#94a3b8',
              'target-arrow-shape': 'triangle',
              'curve-style': 'bezier',
              label: '',
              'font-size': 7,
              'min-zoomed-font-size': 6,
              color: '#64748b',
              'text-background-color': '#ffffff',
              'text-background-opacity': 0.72,
              'text-background-padding': 2,
              opacity: 0.6,
            },
          },
          {
            selector: 'edge.focused',
            style: {
              width: 1.8,
              opacity: 0.92,
            },
          },
        ],
      })

      function clearFocus() {
        cy.elements().removeClass('dimmed focused')
      }

      cy.on('tap', 'node', event => {
        const node = event.target
        const neighborhood = node.closedNeighborhood()
        clearFocus()
        cy.elements().addClass('dimmed')
        neighborhood.removeClass('dimmed')
        neighborhood.addClass('focused')
      })

      cy.on('tap', event => {
        if (event.target === cy) {
          clearFocus()
        }
      })
    } catch (error) {
      meta.textContent = 'Failed to load graph data.'
      container.innerHTML = '<p style="padding: 1rem;">' + String(error) + '</p>'
    }
  }

  loadKbGraph()
</script>
`
}

export function slugify(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80)
}

export interface JekyllPublishFileOptions {
  /**
   * Publish instant (`Date.now()`); emitted YAML `date` is the **local calendar day** derived from
   * this — not SQLite `created_at` / `updated_at`.
   */
  publishedAtMs?: number
}

export function buildJekyllFile(doc: KbDocRow, options?: JekyllPublishFileOptions): string {
  const frontMatter = mapToJekyllFrontMatter(doc, options)
  const body = stripKbMetadataHeader(doc.content)
  return `---\n${yaml.dump(frontMatter, { lineWidth: -1 }).trimEnd()}\n---\n\n${body.trimStart()}`
}

/**
 * Jekyll YAML `date` for published KB pages — **local calendar date only** (no time-of-day).
 * A UTC timestamp from `Date.now()` / `toISOString()` in the front matter is often interpreted as
 * **local** wall time by Jekyll, so evening builds can look “tomorrow” vs `site.time` and the
 * Publisher skips writing HTML (404 while `.md` copies still land in `_site`).
 */
export function formatJekyllPublishSnapshotDate(publishedAtMs: number): string {
  const d = new Date(publishedAtMs)
  const y = d.getFullYear()
  const m = String(d.getMonth() + 1).padStart(2, '0')
  const day = String(d.getDate()).padStart(2, '0')
  return `${y}-${m}-${day}`
}

export function mapToJekyllFrontMatter(
  doc: KbDocRow,
  options?: JekyllPublishFileOptions
): Record<string, unknown> {
  const tags = parseTags(doc.tags_json)
  const publishedAtMs = options?.publishedAtMs ?? Date.now()
  const fm: Record<string, unknown> = {
    layout: 'default',
    title: doc.title,
    date: formatJekyllPublishSnapshotDate(publishedAtMs),
    kb_id: doc.id,
  }
  if (tags.length > 0) fm.tags = tags
  if (doc.doc_type) fm.categories = [doc.doc_type]
  return fm
}

export function stripKbMetadataHeader(content: string): string {
  const lines = content.split('\n')
  let i = 0

  // skip H1 title line
  if (lines[i]?.startsWith('# ')) i++

  // skip blank lines then metadata key-value lines (Created:, Type:, Tags:)
  while (i < lines.length) {
    const line = lines[i]
    if (line.trim() === '') {
      i++
      continue
    }
    if (/^(Created|Type|Tags): /.test(line)) {
      i++
      continue
    }
    break
  }

  return lines.slice(i).join('\n')
}

function parseTags(tagsJson: string | null): string[] {
  if (!tagsJson) return []
  try {
    const parsed = JSON.parse(tagsJson)
    return Array.isArray(parsed) ? parsed.map(String) : []
  } catch {
    return []
  }
}

function deduplicateFilename(base: string, seen: Set<string>): string {
  if (!seen.has(base)) return base
  const ext = path.extname(base)
  const stem = base.slice(0, -ext.length)
  let n = 2
  while (seen.has(`${stem}-${n}${ext}`)) n++
  return `${stem}-${n}${ext}`
}
