/**
 * Notion publish mirrors `jekyll-sync.ts`:
 * - two lanes: originals vs autogenerated (`partitionPublishDocsByOriginalFlag`)
 * - apply: wipe lane contents, rewrite from SQLite
 * - preview: plan writes + report stale pages that would be removed
 *
 * Notion needs a small state file for stable container/section page IDs (Jekyll uses fixed dirs).
 */
import {
  type PublishPageRecord,
  type SqliteDocumentRow,
  partitionPublishDocsByOriginalFlag,
} from './publish-docs'
import {
  type NotionPublishState,
  readNotionPublishState,
  writeNotionPublishState,
} from './publish-state'

const NOTION_VERSION = '2022-06-28'

export interface NotionExistingPage {
  id: string
  title: string
  section: 'original' | 'autogenerated'
}

export interface NotionSyncResult {
  publishedPages: PublishPageRecord[]
  written: Array<{ id: string; title: string; section: 'original' | 'autogenerated' }>
  removed: NotionExistingPage[]
  skipped: Array<{ id: string; title: string; reason: string }>
  warnings: string[]
  containerPageId?: string
  containerUrl?: string
}

export async function syncDocsToNotion(input: {
  token: string
  parentPageId: string
  baseName: string
  baseDir: string
  docs: SqliteDocumentRow[]
  apply: boolean
}): Promise<NotionSyncResult> {
  const { originals, autogenerated } = partitionPublishDocsByOriginalFlag(input.docs)
  const written: NotionSyncResult['written'] = []
  const skipped: NotionSyncResult['skipped'] = []
  const warnings: string[] = []

  for (const docs of [originals, autogenerated]) {
    for (const doc of docs) {
      if (!doc.title?.trim()) {
        skipped.push({ id: doc.id, title: '', reason: 'no title' })
      }
    }
  }

  const publishableOriginals = originals.filter(d => d.title?.trim())
  const publishableAutogenerated = autogenerated.filter(d => d.title?.trim())

  for (const doc of publishableOriginals) {
    written.push({ id: doc.id, title: doc.title, section: 'original' })
  }
  for (const doc of publishableAutogenerated) {
    written.push({ id: doc.id, title: doc.title, section: 'autogenerated' })
  }

  const state = await readNotionPublishState(input.baseDir)
  const existingPages = state
    ? await listSectionPages(input.token, state, warnings)
    : []

  const plannedTitles = new Map<'original' | 'autogenerated', Set<string>>()
  plannedTitles.set('original', new Set(publishableOriginals.map(d => d.title)))
  plannedTitles.set('autogenerated', new Set(publishableAutogenerated.map(d => d.title)))

  const removed = existingPages.filter(
    page => !plannedTitles.get(page.section)?.has(page.title)
  )

  if (!input.apply) {
    return {
      publishedPages: buildPreviewPages(publishableOriginals, publishableAutogenerated),
      written,
      removed,
      skipped,
      warnings,
      containerPageId: state?.containerPageId,
      containerUrl: state?.containerUrl,
    }
  }

  let activeState = state
  if (!activeState) {
    activeState = await createPublishRoot(input.token, input.parentPageId, input.baseName, input.baseDir)
  }

  await wipeSectionPages(input.token, activeState.originalSectionPageId, warnings)
  await wipeSectionPages(input.token, activeState.autogeneratedSectionPageId, warnings)

  const publishedPages: PublishPageRecord[] = [
    {
      id: 'section-original-documents',
      title: 'Original Documents',
      notionPageId: activeState.originalSectionPageId,
      pageRole: 'section',
      section: 'original',
    },
    {
      id: 'section-autogenerated-documents',
      title: 'Autogenerated Documents',
      notionPageId: activeState.autogeneratedSectionPageId,
      pageRole: 'section',
      section: 'autogenerated',
    },
  ]

  for (const doc of publishableOriginals) {
    try {
      const page = await notionCreatePage({
        token: input.token,
        parentPageId: activeState.originalSectionPageId,
        title: doc.title,
        markdown: doc.content,
      })
      publishedPages.push({
        id: doc.id,
        title: doc.title,
        notionPageId: page.id,
        notionUrl: page.url,
        pageRole: 'document',
        section: 'original',
      })
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err)
      warnings.push(`Failed to publish original "${doc.title}": ${msg}`)
    }
  }

  for (const doc of publishableAutogenerated) {
    try {
      const page = await notionCreatePage({
        token: input.token,
        parentPageId: activeState.autogeneratedSectionPageId,
        title: doc.title,
        markdown: doc.content,
      })
      publishedPages.push({
        id: doc.id,
        title: doc.title,
        notionPageId: page.id,
        notionUrl: page.url,
        pageRole: 'document',
        section: 'autogenerated',
      })
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err)
      warnings.push(`Failed to publish autogenerated "${doc.title}": ${msg}`)
    }
  }

  await writeNotionPublishState(input.baseDir, {
    ...activeState,
    updatedAt: new Date().toISOString(),
  })

  return {
    publishedPages,
    written,
    removed,
    skipped,
    warnings,
    containerPageId: activeState.containerPageId,
    containerUrl: activeState.containerUrl,
  }
}

function buildPreviewPages(
  originals: SqliteDocumentRow[],
  autogenerated: SqliteDocumentRow[]
): PublishPageRecord[] {
  const pages: PublishPageRecord[] = [
    {
      id: 'section-original-documents',
      title: 'Original Documents',
      pageRole: 'section',
      section: 'original',
    },
    {
      id: 'section-autogenerated-documents',
      title: 'Autogenerated Documents',
      pageRole: 'section',
      section: 'autogenerated',
    },
  ]
  for (const doc of originals) {
    pages.push({ id: doc.id, title: doc.title, pageRole: 'document', section: 'original' })
  }
  for (const doc of autogenerated) {
    pages.push({ id: doc.id, title: doc.title, pageRole: 'document', section: 'autogenerated' })
  }
  return pages
}

async function createPublishRoot(
  token: string,
  parentPageId: string,
  baseName: string,
  baseDir: string
): Promise<NotionPublishState> {
  const containerPage = await notionCreatePage({
    token,
    parentPageId,
    title: `${baseName} — KB Publish`,
  })
  const originalSection = await notionCreatePage({
    token,
    parentPageId: containerPage.id,
    title: 'Original Documents',
  })
  const autogeneratedSection = await notionCreatePage({
    token,
    parentPageId: containerPage.id,
    title: 'Autogenerated Documents',
  })
  const state: NotionPublishState = {
    version: 1,
    updatedAt: new Date().toISOString(),
    baseName,
    containerPageId: containerPage.id,
    containerUrl: containerPage.url,
    originalSectionPageId: originalSection.id,
    autogeneratedSectionPageId: autogeneratedSection.id,
  }
  await writeNotionPublishState(baseDir, state)
  return state
}

async function listSectionPages(
  token: string,
  state: NotionPublishState,
  warnings: string[]
): Promise<NotionExistingPage[]> {
  const pages: NotionExistingPage[] = []
  for (const [sectionPageId, section] of [
    [state.originalSectionPageId, 'original'],
    [state.autogeneratedSectionPageId, 'autogenerated'],
  ] as const) {
    const childIds = await notionListChildPageIds(token, sectionPageId)
    for (const pageId of childIds) {
      try {
        const title = await notionPageTitle(token, pageId)
        pages.push({ id: pageId, title, section })
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err)
        warnings.push(`Failed to read Notion page ${pageId}: ${msg}`)
      }
    }
  }
  return pages
}

async function wipeSectionPages(
  token: string,
  sectionPageId: string,
  warnings: string[]
): Promise<void> {
  const childPageIds = await notionListChildPageIds(token, sectionPageId)
  for (const pageId of childPageIds) {
    try {
      await notionArchivePage(token, pageId)
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err)
      warnings.push(`Failed to archive Notion page ${pageId}: ${msg}`)
    }
  }
}

async function notionListChildPageIds(token: string, parentPageId: string): Promise<string[]> {
  const ids: string[] = []
  let cursor: string | undefined

  do {
    const url = new URL(`https://api.notion.com/v1/blocks/${parentPageId}/children`)
    url.searchParams.set('page_size', '100')
    if (cursor) url.searchParams.set('start_cursor', cursor)

    const response = await fetch(url, {
      headers: {
        Authorization: `Bearer ${token}`,
        'Notion-Version': NOTION_VERSION,
      },
    })

    if (!response.ok) {
      const body = await response.text()
      throw new Error(`Notion list children failed (${response.status}): ${body}`)
    }

    const parsed = (await response.json()) as {
      results?: Array<{ id?: string; type?: string }>
      has_more?: boolean
      next_cursor?: string | null
    }

    for (const block of parsed.results ?? []) {
      if (block.type === 'child_page' && block.id) ids.push(block.id)
    }

    cursor = parsed.has_more && parsed.next_cursor ? parsed.next_cursor : undefined
  } while (cursor)

  return ids
}

async function notionPageTitle(token: string, pageId: string): Promise<string> {
  const response = await fetch(`https://api.notion.com/v1/pages/${pageId}`, {
    headers: {
      Authorization: `Bearer ${token}`,
      'Notion-Version': NOTION_VERSION,
    },
  })

  if (!response.ok) {
    const body = await response.text()
    throw new Error(`Notion get page failed (${response.status}): ${body}`)
  }

  const parsed = (await response.json()) as {
    properties?: {
      title?: { title?: Array<{ plain_text?: string }> }
    }
  }

  const chunks = parsed.properties?.title?.title ?? []
  return chunks.map(chunk => chunk.plain_text ?? '').join('').trim()
}

async function notionArchivePage(token: string, pageId: string): Promise<void> {
  const response = await fetch(`https://api.notion.com/v1/pages/${pageId}`, {
    method: 'PATCH',
    headers: {
      Authorization: `Bearer ${token}`,
      'Notion-Version': NOTION_VERSION,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ archived: true }),
  })

  if (!response.ok) {
    const body = await response.text()
    throw new Error(`Notion archive page failed (${response.status}): ${body}`)
  }
}

async function notionCreatePage(input: {
  token: string
  parentPageId?: string
  title: string
  markdown?: string
}): Promise<{ id: string; url: string }> {
  const response = await fetch('https://api.notion.com/v1/pages', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${input.token}`,
      'Notion-Version': NOTION_VERSION,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      parent: { page_id: input.parentPageId },
      properties: {
        title: {
          title: [{ type: 'text', text: { content: input.title.slice(0, 200) } }],
        },
      },
      ...(input.markdown ? { markdown: input.markdown } : {}),
    }),
  })

  if (!response.ok) {
    const body = await response.text()
    throw new Error(`Notion create page failed (${response.status}): ${body}`)
  }

  const parsed = (await response.json()) as { id?: string; url?: string }
  if (!parsed.id || !parsed.url) {
    throw new Error('Notion create page response missing id/url')
  }

  return { id: parsed.id, url: parsed.url }
}
