import { readFile, writeFile, mkdir } from 'node:fs/promises'
import path from 'node:path'

/** Stable Notion publish root — mirrors Jekyll `_original_docs` / `_autogenerated_docs` dirs. */
export interface NotionPublishState {
  version: 1
  updatedAt: string
  baseName: string
  containerPageId: string
  containerUrl?: string
  originalSectionPageId: string
  autogeneratedSectionPageId: string
}

export function notionPublishStatePath(baseDir: string): string {
  return path.join(baseDir, '.kb-publish-notion.json')
}

export async function readNotionPublishState(baseDir: string): Promise<NotionPublishState | undefined> {
  try {
    const raw = await readFile(notionPublishStatePath(baseDir), 'utf8')
    const parsed = JSON.parse(raw) as NotionPublishState
    if (parsed?.version !== 1 || !parsed.containerPageId) return undefined
    return parsed
  } catch {
    return undefined
  }
}

export async function writeNotionPublishState(
  baseDir: string,
  state: NotionPublishState
): Promise<void> {
  await mkdir(baseDir, { recursive: true })
  await writeFile(notionPublishStatePath(baseDir), `${JSON.stringify(state, null, 2)}\n`, 'utf8')
}
