import path from 'node:path'
import { SqliteKbIndexer } from '@kb/core/tools/sqlite-kb-index.js'
import { ensureOperationalBaseDir, resolveEffectiveBaseDir } from '@kb/core/storage/base-selection.js'
import { readKbConfig, resolveNotionToken } from '@kb/core/config/kb-config.js'
import { syncDocsToNotion } from '@kb/core/core/publish/notion-sync.js'
import {
  type PublishPageRecord,
  type SqliteDocumentRow,
  partitionPublishDocsByOriginalFlag,
} from '@kb/core/core/publish/publish-docs.js'

export type { PublishPageRecord, SqliteDocumentRow }
export { partitionPublishDocsByOriginalFlag }

export type PublishPhase = 'all' | 'import' | 'restructure'
export type PublishStopPoint = string

export interface PublishOptions {
  base?: string
  phase: PublishPhase
  apply: boolean
  parentPageId?: string
  stagePageId?: string
  checkpointFile?: string
  resumeFrom?: string
  stopAfter?: PublishStopPoint
  progressSink?: (line: string) => void
}

export interface PublishRemovedPage {
  id: string
  title: string
  section: 'original' | 'autogenerated'
}

export interface PublishResult {
  status: 'accepted' | 'preview'
  apply: boolean
  baseName: string
  baseDir: string
  totalDocs: number
  publishedPages: PublishPageRecord[]
  removedPages: PublishRemovedPage[]
  warnings: string[]
  containerPageId?: string
  containerUrl?: string
}

class PublishProgressReporter {
  private completed = 0

  constructor(
    private total: number,
    private sink: (line: string) => void = line => process.stderr.write(line)
  ) {}

  start(label: string, detail?: string) {
    this.render(label, detail)
  }

  finish(label: string, detail?: string) {
    this.completed += 1
    this.render(label, detail)
  }

  update(label: string, detail?: string) {
    this.render(label, detail)
  }

  private render(label: string, detail?: string) {
    const width = 24
    const filled = Math.round((this.completed / Math.max(this.total, 1)) * width)
    const bar = `${'='.repeat(filled)}${'-'.repeat(Math.max(width - filled, 0))}`
    const suffix = detail ? ` ${detail}` : ''
    this.sink(`[publish] [${bar}] ${this.completed}/${this.total} ${label}${suffix}\n`)
  }
}

export function parsePublishCommand(args: string[]): PublishOptions {
  const hasApply = readFlag(args, '--apply')
  const phase = (readOption(args, '--phase') ?? 'all') as PublishPhase
  if (!['all', 'import', 'restructure'].includes(phase)) {
    throw new Error('Invalid --phase. Use all|import|restructure')
  }

  const stopAfter = readOption(args, '--stop-after')?.trim().toLowerCase()

  return {
    base: readOption(args, '--base'),
    phase,
    apply: hasApply,
    parentPageId: readOption(args, '--parent-page-id'),
    stagePageId: readOption(args, '--stage-page-id'),
    checkpointFile: readOption(args, '--checkpoint-file'),
    resumeFrom: readOption(args, '--resume-from'),
    stopAfter,
  }
}

export async function runPublishCommand(
  options: PublishOptions,
  cwd: string = process.cwd()
): Promise<PublishResult> {
  const config = await readKbConfig()
  const baseResolution = await resolvePublishBase(options.base, cwd)
  const warnings: string[] = []

  const token = options.apply ? resolveNotionToken(config) : undefined
  if (options.apply && !token) {
    throw new Error(
      'Missing Notion token. Set notion.token in ~/.kb/config.json or NOTION_TOKEN/NOTION_API_KEY in env.'
    )
  }

  const parentPageId =
    options.parentPageId ?? config.notion?.parentPageId ?? process.env.NOTION_PARENT_PAGE_ID

  if (options.apply && !parentPageId) {
    throw new Error(
      'Missing Notion parent page ID. Set notion.parentPageId in ~/.kb/config.json or --parent-page-id flag.'
    )
  }

  const sqliteDbPath = path.join(baseResolution.baseDir, '.kb-index.sqlite')
  const docs = readDocumentsFromSqlite(sqliteDbPath)

  if (docs.length === 0) {
    warnings.push('No documents found in SQLite database. Run `kb init` to populate.')
  }

  const progressTotal = 2 + docs.length
  const progress = new PublishProgressReporter(progressTotal, options.progressSink)
  progress.start('reading docs', `${docs.length} documents`)

  if (!options.apply) {
    const syncResult = await syncDocsToNotion({
      token: token ?? 'preview-token',
      parentPageId: parentPageId ?? 'preview-parent',
      baseName: baseResolution.baseName,
      baseDir: baseResolution.baseDir,
      docs,
      apply: false,
    })

    for (const page of syncResult.publishedPages.filter(p => p.pageRole === 'section')) {
      progress.finish('preview', page.title)
    }
    for (const page of syncResult.publishedPages.filter(p => p.pageRole === 'document')) {
      progress.finish('preview', page.title)
    }
    for (const removed of syncResult.removed) {
      progress.finish('would remove', removed.title)
    }

    return {
      status: 'preview',
      apply: false,
      baseName: baseResolution.baseName,
      baseDir: baseResolution.baseDir,
      totalDocs: docs.length,
      publishedPages: syncResult.publishedPages,
      removedPages: syncResult.removed,
      warnings: [...warnings, ...syncResult.warnings],
      containerPageId: syncResult.containerPageId,
      containerUrl: syncResult.containerUrl,
    }
  }

  if (!token || !parentPageId) {
    throw new Error('Notion token and parent page ID are required to publish.')
  }

  const syncResult = await syncDocsToNotion({
    token,
    parentPageId,
    baseName: baseResolution.baseName,
    baseDir: baseResolution.baseDir,
    docs,
    apply: true,
  })

  progress.update('synced container', syncResult.containerUrl ?? syncResult.containerPageId ?? '')

  for (const page of syncResult.publishedPages.filter(p => p.pageRole === 'section')) {
    progress.finish('section', page.title)
  }
  for (const page of syncResult.publishedPages.filter(p => p.pageRole === 'document')) {
    progress.finish('published', page.title)
  }
  for (const removed of syncResult.removed) {
    progress.finish('removed', removed.title)
  }

  return {
    status: 'accepted',
    apply: true,
    baseName: baseResolution.baseName,
    baseDir: baseResolution.baseDir,
    totalDocs: docs.length,
    publishedPages: syncResult.publishedPages,
    removedPages: syncResult.removed,
    warnings: [...warnings, ...syncResult.warnings],
    containerPageId: syncResult.containerPageId,
    containerUrl: syncResult.containerUrl,
  }
}

export function readDocumentsFromSqlite(dbPath: string): SqliteDocumentRow[] {
  try {
    const indexer = new SqliteKbIndexer({ dbPath })
    const docs = indexer.listPublishableDocs()
    indexer.close()
    return docs
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    throw new Error(`Cannot read SQLite at ${dbPath}: ${msg}`)
  }
}

export async function resolvePublishBase(
  base: string | undefined,
  cwd: string
): Promise<{ baseName: string; baseDir: string }> {
  if (base?.trim()) {
    return {
      baseName: base.trim(),
      baseDir: await ensureOperationalBaseDir(base.trim(), cwd),
    }
  }

  const resolved = await resolveEffectiveBaseDir(cwd)
  return {
    baseName: resolved.baseName ?? 'default',
    baseDir: resolved.baseDir,
  }
}

function readOption(args: string[], key: string): string | undefined {
  const idx = args.indexOf(key)
  if (idx === -1) return undefined
  const value = args[idx + 1]
  if (!value || value.startsWith('--')) {
    throw new Error(`${key} requires a value`)
  }
  return value
}

function readFlag(args: string[], key: string): boolean {
  return args.includes(key)
}
